### ISSUE TITLE
Configurar modulo para opção de correios sem contrato

### ISSUE THREAD

**Issue by GabrielaColpas** [tezusecommerce/Tezus_Correios#21]
Fiz a instalação do modulo, e entre as opções de entrega listadas, não há nenhuma que especifique ser do método sem contrato (como mostrado na imagem de Shipment Type). Como faço pra ativar essa funcionalidade? há necessidade de contratação de algum pacote? Segue a lista de metodos disponíveis 
SEDEX A VISTA                 , SEDEX ON LINE A VISTA         , PAC ON LINE A VISTA           , SEDEX A VISTA PGTO NA ENTREGA , SPP A VISTA E A FATURAR       , SPP A VISTA E A FATURAR       , COMBO SEDEX A VISTA           , SEDEX CONTRATO GRAND FORMATOS , SEDEX CONTR GRAND FORMATOS LM , SEDEX CONTRATO AGENCIA LM     , SEDEX CONTRATO AGENCIA        , SEDEX REVERSO ESPELHO 04162   , SEDEX CONTR AGENCIA PAGTO ENTR, COMBO SEDEX CONTRATO AGENCIA  , CORREIOS MINI ENVIOS CTR AG   , SEDEX REVERSO 04170 LM        , SEDEX CONTR AG PAGTO ENTREG LM, SEDEX CONTRATO UO LM          , PAC CONTR AG PAGTO ENTREGA LM , SEDEX CONTRATO   UO           , PAC CONTRATO UO LM            , COMBO SEDEX CONT AG AR ELET LM, COMBO SEDEX CONTRATO AGENCI LM, PAC CONTRATO AGENCIA LM       , PAC REVERSO 04677 LM          , PAC CONTR GRANDES FORMATOS LM , SEDEX 12 SCADA A VISTA        , SEDEX 12 REVERSO SGPB A FATURA, SEDEX 10 SCADA A VISTA        , SEDEX HOJE SCADA  A VISTA FATU, SEDEX HOJE REVERSO SGPB FATURA, COMBO SEDEX 10 SCADA A VISTA  , COMBO SEDEX HOJE SCADA VIST FA, COMBO SEDEX 12 SCADA A VISTA  , COMBO SEDEX 12 AR ELETR SCADA , COMBO SEDEX 10 AR ELETR SCADA , PAC A VISTA                   , COMBO SEDEX HOJE AR ELET SCADA, SEDEX CONTRATO GRANDES FORMATO, SEDEX CONTRATO AGENCIA TA     , SEDEX CONT AG PAG ENT TA      , COMBO SEDEX CONT AG TA        , PAC CONTRATO AGENCIA TA       , PAC CONT AG PAG ENT TA        , PAC CONTRATO GRANDES FORMATOS , PAC CONTRATO AGENCIA          , PAC REVERSO ESPELHO 04669     , PAC CONTRATO AGENCIA PAGTO ENT, PAC CONTRATO GRANDES FORMATOS , PAC A VISTA PAGTO NA ENTREGA  , COMBO PAC A VISTA             , PAC CONTRATO   UO             , COMBO SEDEX A VISTA AR ELETRON, COMBO SEDEX A VISTA EMBALAGEM , COMBO PAC A VISTA EMBALAGEM   , SEDEX REVERSO TA ESPELHO 04553, PAC REVERSO TA ESPELHO 04596  , SEDEX CORREIOS LOG            , PAC CORREIOS LOG              , SEDEX A VISTA SCADA           , SEDEX A COBRAR                , SEDEX (CONTRATO)              , SEDEX A COBRAR ENCOMENDA      , SERVICO DE PROTOCOLO POSTAL   , SEDEX 12 A FATURAR            , SEDEX ADMINISTRATIVO CSHOPPING, SEDEX 10 A FATURAR            , SEDEX 10 ENCOMENDA            , SEDEX HOJE A FATURAR          , SEDEX REVERSO 40096           , SEDEX REVERSO 40436           , SEDEX   CONTRATO              , SEDEX   CONTRATO              , SEDEX REVERSO 40444           , SEDEX ADMINISTRATIVO          , SEDEX   CONTRATO              , SEDEX REVERSO   CONTRATO      , SEDEX 10 REVERSO A FATURAR    , SEDEX   CONTRATO              , SEDEX REVERSO   CONTRATO      , SEDEX PAGAMENTO NA ENTREGA    , SEDEX 10                      , SEDEX 10 REVERSO              , SEDEX PAGAMENTO NA ENTREGA    , SEDEX HOJE   ROLO E PACOTE    , SEDEX 10   PACOTE E ROLO      , SEDEX 12  PACOTE E  ROLO      , COMBO SEDEX 10 A FATURAR      , COMBO SEDEX A VISTA SCADA     , COMBO SEDEX HOJE A FATURAR    , PAC                           , PAC REVERSO 4106 8            , PAC À VISTA SCADA             , PAC ADMINISTRATIVO            , PAC   CONTRATO                , PAC   REVERSO DO 4121 1       , PAC   PAGAMENTO NA ENTREGA    , PAC ADMINISTRATIVO CSHOPPING  , PAC PAGAMENTO NA ENTREGA      , SEDEX   GRANDES FORMATOS      , PAC GRANDES FORMATOS          , SEDEX GRANDES FORMATOS        , SEDEX REPOSTAGEM              , SEDEX PAGAMENTO NA ENTREGA    , SEDEX PAGAMENTO NA ENTREGA    , COMBO PAC A VISTA SCADA       , COMBO SEDEX CONTRATO          , COMBO SEDEX 12 A FATURAR      , PAC REPOSTAGEM                , PAC INTERM E COMMERCE TAB41068, SEDEX INTERM E COMMERCE 40096 , SEDEX PRE PAGO VIA INTERNET   , SEDEX 10 PRE PAGO VIA INTERNET, SEDEX 12 PRE PAGO VIA INTERNET, SEDEX HOJE PRE PAGO VIA INTERN, PAC PRE PAGO VIA INTERNET     , REMESSA AGRUPADA PAC          , REMESSA AGRUPADA PAC N POLIT  , COMBO SEDEX ELEICOES          , COMBO SEDEX HOJE ELEICOES     , COMBO SEDEX 10 ELEICOES       , COMBO PAC ELEICOES            , COMBO SEDEX 12 ELEICOES       , SEDEX REPOSTAGEM REVERSO      , PAC REPOSTAGEM REVERSO        , TAXA DE ARMAZENAGEM           , ENTREGA EXPRESSA              , CARGA CONSOLIDADA EXPRESSA ES , E SEDEX STANDARD              , E SEDEX PRIORITARIO           , E SEDEX EXPRESS               , E SEDEX  REVERSO              , E SEDEX ADMINISTRATIVO CSHOP  , E SEDEX INTERM E COMMERCE     , E SEDEX GRUPO II              , E SEDEX  REVERSO GRUPO II     , E SEDEX TOCANTINS             , E SEDEX GRUPO I               , E SEDEX  REVERSO GRUPO I

**Comment by Samuel291** [comment]
Olá Gabriela, boa tarde! 
Verificando sua issue pesquisei no google quais são os códigos mais recentes para PAC e SEDEX sem contrato, após isso busquei no link: http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/ListaServicos
Pelo código referente aos métodos sem contrato e verifiquei que os Métodos que você precisa marcar são:
SEDEX A VISTA SCADA que é referente ao SEDEX sem contrato código 40010
PAC À VISTA SCADA que é referente ao PAC sem contrato código 41106

**Comment by LucasPereira762xi** [comment]
Feature was implemented and now you can use edit all Correios codes
