### ISSUE TITLE
Como eu faço para usar codigos diferentes de Correios?

### ISSUE THREAD

**Issue by pedrohenrique1986** [tezusecommerce/Tezus_Correios#22]
Olá, como eu faço para usar codigos diferentes de PAC e SEDEX com contrato?

Exemplo, o modulo usa o codigo PAC com Contrato = 41068

Se quiser usar  um diferente? Onde posso alterar esse codigo?
Obrigado

**Comment by LucasPereira762xi** [comment]
Featured was implemented and now you can use edit all Correios codes
