### ISSUE TITLE
Problema para versão 2.4.4 (PHP8.1)

### ISSUE THREAD

**Issue by lagunde** [tezusecommerce/Tezus_Correios#23]
O módulo apresenta um problema para a última versão do magento. 

1 exception(s):
Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Tezus\Correios\Logger\Logger, Monolog\Logger::__construct(): Argument #1 ($name) must be of type string, array given, called in /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

**Comment by guiserinoli** [comment]
Algum retorno?

**Comment by guiserinoli** [comment]
No \Logger\Logger.php:

<?php

namespace Tezus\Correios\Logger;

use Monolog\Logger as MonologLogger;

class Logger extends MonologLogger {
    **public function __construct(){}**
}

**Comment by LucasPereira762xi** [comment]
Solved
