### ISSUE TITLE
Magento 2.4.2 / PHP 7.4 Error

### ISSUE THREAD

**Issue by corpsysgit** [tezusecommerce/Tezus_Correios#7]
After command: 
bin/magento setup:upgrade

Result:
Warning: call_user_func() expects parameter 1 to be a valid callback, class 'Tezus\Correios\Setup\Patch\Data\AddAlturaCorreiosProductAttribute' not found in /home/melbourne/public_html/vendor/magento/framework/Setup/Patch/PatchRegistry.php on line 141

**Comment by Moi250** [comment]
Olá boa noite amigo, estou com o mesmo problema, você conseguiu solucionar? Teria outro modulo de frete dos correios para indicar?

**Comment by luisseidel** [comment]
A princípio o módulo está funcionando normalmente agora.
